apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc-gateway
  namespace: default
  labels:
    app: svc-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: svc-gateway
  template:
    metadata:
      labels:
        app: svc-gateway
    spec:
      containers:
      - name: svc-gateway
        image: ghcr.io/gh-aakash/billionbrains/svc-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: http
        env:
        - name: USER_SERVICE_URL
          value: "http://svc-identity:50051"
        - name: IDEA_SERVICE_URL
          value: "http://svc-brain-core:50052"
        - name: NATS_URL
          value: "nats:4222"
        - name: RUST_LOG
          value: "info"
---
apiVersion: v1
kind: Service
metadata:
  name: svc-gateway
  namespace: default
spec:
  ports:
  - port: 4000
    targetPort: 4000
    name: http
  selector:
    app: svc-gateway
